version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_instance
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  order_service:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sql_server
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql_server;Database=OrderServiceDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=rabbituser
      - RabbitMQ__Password=rabbitpassword
      - Jwt__Key=cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
      - Jwt__Issuer=Unosquare
      - Jwt__Audience=OrderService
      - Jwt__ExpirationMinutes=30
    networks:
      - app-network

  product_service:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - sql_server
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql_server;Database=ProductServiceDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=rabbituser
      - RabbitMQ__Password=rabbitpassword
      - Jwt__Key=cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
      - Jwt__Issuer=Unosquare
      - Jwt__Audience=ProductService
      - Jwt__ExpirationMinutes=30
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpassword
  customer_service:
    build:
      context: .
      dockerfile: CustomerService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - sql_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql_server;Database=CustomerServiceDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=rabbituser
      - RabbitMQ__Password=rabbitpassword
      - Jwt__Key=cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
      - Jwt__Issuer=Unosquare
      - Jwt__Audience=CustomerService
      - Jwt__ExpirationMinutes=30
    networks:
      - app-network


networks:
  app-network:

volumes:
  sql_data: 